// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqqcuqhooyrwdkytfmep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxcWN1cWhvb3lyd2RreXRmbWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTk2MDUsImV4cCI6MjA3MDMzNTYwNX0.eB6V03RA5lben2OUJr838BW0suKqtD1E19Jh8udVbjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});